#############ubuntu############
FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install gcc zlib1g-dev musl-dev make ffmpeg openssl libssl-dev wget unzip libpcre3 libpcre3-dev python3 python3-pip -y && \
    wget https://github.com/arut/nginx-rtmp-module/archive/afd350e0d8b7820d7d2cfc3fa748217153265ce6.zip && \
    unzip  afd350e0d8b7820d7d2cfc3fa748217153265ce6.zip

RUN wget https://nginx.org/download/nginx-1.19.0.tar.gz && \
    tar zxf nginx-1.19.0.tar.gz && \
    cd nginx-1.19.0 && \
    ./configure --add-module=/nginx-rtmp-module-afd350e0d8b7820d7d2cfc3fa748217153265ce6 && \
    make && \
    make install