#############ubuntu############
FROM  docker.io/howcansheslap/nginx-rtmp-server:1.0.0

COPY nginx.conf /usr/local/nginx/conf/
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY entrypoint.sh entrypoint.sh

COPY ffmpeg.py ffmpeg.py
CMD ["/bin/sh", "entrypoint.sh"]

