apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: live-caption
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
      - name: english-model
        hostPath:
          path: /models/english
      containers:
      - name: backend
        image: docker.io/howcansheslap/livecaption-backend:1.0.1
        volumeMounts:
        - mountPath: /models/english
          name: english-model
        ports:
        - containerPort: 1935
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: live-caption
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: stream-rtmp
  namespace: live-caption
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 1935
      targetPort: 1935



---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: live-caption
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - livecaption-backend.alsabagtech.com
    secretName: tls-secret
  rules:
  - host: livecaption-backend.alsabagtech.com
    http:
      paths:
      - backend:
          serviceName: backend
          servicePort: 80
        path: /(.*)
